version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t $DOCKER_USER/circleci-loudml .
          docker push $DOCKER_USER/circleci-loudml
